name: 'Setup Ruby Environment'
description: 'Sets up Ruby with bundler caching and common dependencies'

inputs:
  ruby-version:
    description: 'Ruby version to use'
    required: false
    default: '3.2'
  install-system-deps:
    description: 'Install system dependencies (jq)'
    required: false
    default: 'true'
  bundler-cache:
    description: 'Enable bundler caching (set to false for version bump workflows)'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Ruby ${{ inputs.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: ${{ inputs.bundler-cache }}
        # Ensure bundler >= 2.3 for compatibility with gemspec requirements
        bundler: '2.5'

    - name: Install system dependencies
      if: inputs.install-system-deps == 'true'
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y jq

    - name: Disable frozen mode for development workflows
      if: inputs.bundler-cache != 'true'
      shell: bash
      run: |
        bundle config set --local frozen false
        bundle config unset deployment 2>/dev/null || true

    - name: Ensure Ruby dependencies are installed
      shell: bash
      run: |
        bundle check || bundle install --jobs 4 --retry 3

    - name: Make scripts executable
      shell: bash
      run: chmod +x scripts/*.sh test/*.sh 2>/dev/null || true