#!/bin/bash

# =============================================================================
# Configuration Matrix Generator for zer0-mistakes Jekyll Theme
# =============================================================================
# 
# Generates Jekyll site configurations for each installation mode.
# Used for testing different theme installation methods.
#
# Installation Modes:
#   - full:         Complete local installation with all theme files
#   - minimal:      Essential files only (config, Gemfile, index)
#   - remote_theme: GitHub Pages remote_theme configuration
#   - gem:          Ruby gem-based theme installation
#
# Usage:
#   ./config_matrix_generator.sh --mode <mode> --output <directory>
#   ./config_matrix_generator.sh --all --output-base <base_directory>
#

set -euo pipefail

# Script configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Available installation modes
readonly INSTALL_MODES=("full" "minimal" "remote_theme" "gem")

# Color output
readonly GREEN='\033[0;32m'
readonly BLUE='\033[0;34m'
readonly YELLOW='\033[1;33m'
readonly RED='\033[0;31m'
readonly NC='\033[0m'

# =============================================================================
# LOGGING
# =============================================================================

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# =============================================================================
# CONFIGURATION GENERATORS
# =============================================================================

# Generate _config.yml for full local installation
generate_full_config() {
    local output_dir="$1"
    
    log_info "Generating full installation configuration..."
    
    # Copy the actual _config.yml from the project
    if [[ -f "$PROJECT_ROOT/_config.yml" ]]; then
        cp "$PROJECT_ROOT/_config.yml" "$output_dir/_config.yml"
    else
        # Generate a minimal config if source doesn't exist
        cat > "$output_dir/_config.yml" << 'EOF'
# Full Installation Configuration
# Generated by config_matrix_generator.sh

title: "zer0-mistakes Test Site (Full)"
description: "Test site generated with full installation mode"
baseurl: ""
url: ""

# Theme configuration - full local installation
# All theme files are included locally

# Essential plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:slug/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - test/
EOF
    fi
    
    # Copy _config_dev.yml if exists
    if [[ -f "$PROJECT_ROOT/_config_dev.yml" ]]; then
        cp "$PROJECT_ROOT/_config_dev.yml" "$output_dir/_config_dev.yml"
    fi
}

# Generate _config.yml for minimal installation
generate_minimal_config() {
    local output_dir="$1"
    
    log_info "Generating minimal installation configuration..."
    
    cat > "$output_dir/_config.yml" << 'EOF'
# Minimal Installation Configuration
# Generated by config_matrix_generator.sh

title: "zer0-mistakes Test Site (Minimal)"
description: "Test site generated with minimal installation mode"
baseurl: ""
url: ""

# Minimal plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Basic markdown processing
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
EOF
}

# Generate _config.yml for remote_theme installation
generate_remote_theme_config() {
    local output_dir="$1"
    
    log_info "Generating remote_theme installation configuration..."
    
    cat > "$output_dir/_config.yml" << 'EOF'
# Remote Theme Installation Configuration
# Generated by config_matrix_generator.sh
# For use with GitHub Pages

title: "zer0-mistakes Test Site (Remote Theme)"
description: "Test site generated with remote_theme installation mode"
baseurl: ""
url: ""

# Remote theme configuration
remote_theme: "bamr87/zer0-mistakes"

# Required plugins for GitHub Pages remote theme
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Collections (inherited from remote theme but can be customized)
collections:
  docs:
    output: true
    permalink: /:collection/:name/
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:slug/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
EOF
}

# Generate _config.yml for gem-based installation
generate_gem_config() {
    local output_dir="$1"
    
    log_info "Generating gem-based installation configuration..."
    
    cat > "$output_dir/_config.yml" << 'EOF'
# Gem-Based Theme Installation Configuration
# Generated by config_matrix_generator.sh

title: "zer0-mistakes Test Site (Gem Theme)"
description: "Test site generated with gem-based theme installation"
baseurl: ""
url: ""

# Gem theme configuration
theme: "jekyll-theme-zer0"

# Essential plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Collections (inherited from gem theme but can be customized)
collections:
  docs:
    output: true
    permalink: /:collection/:name/
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:slug/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
EOF
}

# =============================================================================
# GEMFILE GENERATORS
# =============================================================================

# Generate Gemfile for full installation
generate_full_gemfile() {
    local output_dir="$1"
    
    cat > "$output_dir/Gemfile" << 'EOF'
source "https://rubygems.org"

# GitHub Pages gem includes Jekyll and compatible plugins
gem "github-pages", group: :jekyll_plugins

# Essential plugins
gem "jekyll-remote-theme"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-paginate"

# Platform compatibility
gem "webrick", "~> 1.7"
EOF
}

# Generate Gemfile for minimal installation
generate_minimal_gemfile() {
    local output_dir="$1"
    
    cat > "$output_dir/Gemfile" << 'EOF'
source "https://rubygems.org"

# Jekyll core
gem "jekyll", "~> 4.3"

# Essential plugins
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"

# Platform compatibility
gem "webrick", "~> 1.7"
EOF
}

# Generate Gemfile for remote_theme installation
generate_remote_theme_gemfile() {
    local output_dir="$1"
    
    cat > "$output_dir/Gemfile" << 'EOF'
source "https://rubygems.org"

# GitHub Pages gem (required for remote_theme)
gem "github-pages", group: :jekyll_plugins

# Remote theme plugin
gem "jekyll-remote-theme"

# Additional plugins
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-paginate"

# Platform compatibility
gem "webrick", "~> 1.7"
EOF
}

# Generate Gemfile for gem-based installation
generate_gem_gemfile() {
    local output_dir="$1"
    
    cat > "$output_dir/Gemfile" << 'EOF'
source "https://rubygems.org"

# Jekyll core
gem "jekyll", "~> 4.3"

# Theme gem
gem "jekyll-theme-zer0"

# Essential plugins
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-paginate"

# Platform compatibility
gem "webrick", "~> 1.7"
EOF
}

# =============================================================================
# CONTENT GENERATORS
# =============================================================================

# Generate index page
generate_index_page() {
    local output_dir="$1"
    local mode="$2"
    
    cat > "$output_dir/index.md" << EOF
---
layout: default
title: Home
---

# Welcome to zer0-mistakes Test Site

This site was generated using the **${mode}** installation mode.

## Installation Mode: ${mode}

This is a test site created by the configuration matrix generator
for testing the zer0-mistakes Jekyll theme.

## Test Content

- [About](/about/)
- [Documentation](/docs/)

---

Generated on: $(date -Iseconds)
Mode: ${mode}
EOF
}

# Generate about page
generate_about_page() {
    local output_dir="$1"
    local mode="$2"
    
    mkdir -p "$output_dir/pages"
    
    cat > "$output_dir/pages/about.md" << EOF
---
layout: default
title: About
permalink: /about/
---

# About This Test Site

This site was generated using the **${mode}** installation mode
of the zer0-mistakes Jekyll theme.

## Purpose

This site is used for automated testing to verify that the theme
works correctly across different installation methods.

## Configuration

- Installation Mode: ${mode}
- Generated: $(date -Iseconds)
EOF
}

# Generate a sample docs page
generate_docs_page() {
    local output_dir="$1"
    local mode="$2"
    
    mkdir -p "$output_dir/pages/_docs"
    
    cat > "$output_dir/pages/_docs/getting-started.md" << EOF
---
layout: default
title: Getting Started
permalink: /docs/getting-started/
---

# Getting Started

Welcome to the documentation for the zer0-mistakes test site.

## Installation Mode

This site uses the **${mode}** installation mode.

## Next Steps

1. Explore the site structure
2. Check the configuration
3. Test the theme features
EOF
}

# =============================================================================
# SITE GENERATION
# =============================================================================

# Generate a complete site for a given mode
generate_site() {
    local mode="$1"
    local output_dir="$2"
    
    log_info "Generating site for mode: $mode"
    log_info "Output directory: $output_dir"
    
    # Create output directory
    mkdir -p "$output_dir"
    
    # Generate configuration based on mode
    case "$mode" in
        full)
            generate_full_config "$output_dir"
            generate_full_gemfile "$output_dir"
            
            # Copy theme directories for full installation
            if [[ -d "$PROJECT_ROOT/_layouts" ]]; then
                cp -r "$PROJECT_ROOT/_layouts" "$output_dir/"
            fi
            if [[ -d "$PROJECT_ROOT/_includes" ]]; then
                cp -r "$PROJECT_ROOT/_includes" "$output_dir/"
            fi
            if [[ -d "$PROJECT_ROOT/_sass" ]]; then
                cp -r "$PROJECT_ROOT/_sass" "$output_dir/"
            fi
            if [[ -d "$PROJECT_ROOT/assets" ]]; then
                cp -r "$PROJECT_ROOT/assets" "$output_dir/"
            fi
            if [[ -d "$PROJECT_ROOT/_data" ]]; then
                cp -r "$PROJECT_ROOT/_data" "$output_dir/"
            fi
            ;;
        minimal)
            generate_minimal_config "$output_dir"
            generate_minimal_gemfile "$output_dir"
            ;;
        remote_theme)
            generate_remote_theme_config "$output_dir"
            generate_remote_theme_gemfile "$output_dir"
            ;;
        gem)
            generate_gem_config "$output_dir"
            generate_gem_gemfile "$output_dir"
            ;;
        *)
            log_error "Unknown mode: $mode"
            log_error "Available modes: ${INSTALL_MODES[*]}"
            return 1
            ;;
    esac
    
    # Generate content pages
    generate_index_page "$output_dir" "$mode"
    generate_about_page "$output_dir" "$mode"
    generate_docs_page "$output_dir" "$mode"
    
    # Create collections directory for posts
    mkdir -p "$output_dir/pages/_posts"
    
    # Generate a sample post
    cat > "$output_dir/pages/_posts/$(date +%Y-%m-%d)-test-post.md" << EOF
---
layout: default
title: "Test Post for ${mode} Mode"
date: $(date -Iseconds)
categories: test
---

# Test Post

This is a test post generated for the **${mode}** installation mode.

## Content

Lorem ipsum dolor sit amet, consectetur adipiscing elit. This post
is used to verify that the Jekyll build process works correctly.

## Metadata

- Mode: ${mode}
- Generated: $(date -Iseconds)
EOF
    
    log_success "Site generated successfully for mode: $mode"
}

# Generate all sites
generate_all_sites() {
    local output_base="$1"
    
    log_info "Generating sites for all installation modes..."
    log_info "Output base: $output_base"
    
    for mode in "${INSTALL_MODES[@]}"; do
        local mode_dir="$output_base/$mode"
        generate_site "$mode" "$mode_dir"
    done
    
    log_success "All sites generated successfully"
}

# =============================================================================
# CLI INTERFACE
# =============================================================================

show_help() {
    cat << EOF
Configuration Matrix Generator for zer0-mistakes Jekyll Theme

USAGE:
    $0 [OPTIONS]

DESCRIPTION:
    Generates Jekyll site configurations for testing different installation modes.

OPTIONS:
    -m, --mode MODE       Generate site for specific mode (full, minimal, remote_theme, gem)
    -o, --output DIR      Output directory for generated site
    -a, --all             Generate sites for all installation modes
    -b, --output-base DIR Base directory for all generated sites (used with --all)
    -l, --list            List available installation modes
    -h, --help            Show this help message

MODES:
    full          Complete local installation with all theme files
    minimal       Essential files only (config, Gemfile, index)
    remote_theme  GitHub Pages remote_theme configuration
    gem           Ruby gem-based theme installation

EXAMPLES:
    # Generate a single site
    $0 --mode full --output ./test-site-full

    # Generate all sites
    $0 --all --output-base ./test-sites

    # List available modes
    $0 --list
EOF
}

list_modes() {
    echo "Available installation modes:"
    for mode in "${INSTALL_MODES[@]}"; do
        echo "  - $mode"
    done
}

# =============================================================================
# MAIN
# =============================================================================

main() {
    local mode=""
    local output_dir=""
    local output_base=""
    local generate_all=false
    
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            -m|--mode)
                mode="$2"
                shift 2
                ;;
            -o|--output)
                output_dir="$2"
                shift 2
                ;;
            -a|--all)
                generate_all=true
                shift
                ;;
            -b|--output-base)
                output_base="$2"
                shift 2
                ;;
            -l|--list)
                list_modes
                exit 0
                ;;
            -h|--help)
                show_help
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                show_help
                exit 1
                ;;
        esac
    done
    
    # Validate arguments
    if [[ "$generate_all" == "true" ]]; then
        if [[ -z "$output_base" ]]; then
            log_error "Output base directory required with --all"
            exit 1
        fi
        generate_all_sites "$output_base"
    elif [[ -n "$mode" ]]; then
        if [[ -z "$output_dir" ]]; then
            log_error "Output directory required with --mode"
            exit 1
        fi
        generate_site "$mode" "$output_dir"
    else
        log_error "Either --mode or --all must be specified"
        show_help
        exit 1
    fi
}

# Run main if script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
