#!/usr/bin/env bash
# =============================================================================
# bump-theme-pins.sh — update this repo's zer0-mistakes version pins
# =============================================================================
#
# Copy this into a consumer repo (conventionally scripts/bump-theme-pins.sh).
# It rewrites every place a zer0-mistakes version is pinned, in one pass:
#
#   remote_theme : "bamr87/zer0-mistakes@vX.Y.Z"    _config*.yml
#   theme_repo   : bamr87/zer0-mistakes@vX.Y.Z      _data/hub.yml  (org hubs)
#   gem "jekyll-theme-zer0", "~> X.Y.Z"             Gemfile, Gemfile.azure
#
# The point is that these drift apart. bashconsultants pins the theme in three
# files across three build stacks (Pages / Azure / local); when only one moves,
# two stacks render different theme versions and the difference shows up as a
# rendering bug nobody can reproduce.
#
# Runs standalone (`./bump-theme-pins.sh --latest`) or from the theme-bump
# workflow on a schedule / on a `theme-release` dispatch from the theme repo.
#
# Portability: uses perl, not sed -i, which differs between GNU and BSD.
#
# Usage:
#   ./bump-theme-pins.sh --latest              # bump to newest published release
#   ./bump-theme-pins.sh --version 1.27.0      # bump to a specific version
#   ./bump-theme-pins.sh --check --latest      # exit 1 if behind; write nothing
#   ./bump-theme-pins.sh --latest --dry-run    # show the diff, change nothing
#   ./bump-theme-pins.sh --latest --pin        # also pin refs floating on main
# =============================================================================

set -euo pipefail

THEME_REPO="bamr87/zer0-mistakes"
THEME_GEM="jekyll-theme-zer0"

VERSION=""
USE_LATEST=false
CHECK=false
DRY_RUN=false
PIN_FLOATING=false
FILES=()

usage() { sed -n '2,32p' "$0" | sed 's/^# \{0,1\}//'; }

while [[ $# -gt 0 ]]; do
    case $1 in
        --version)  VERSION="${2#v}"; shift ;;
        --latest)   USE_LATEST=true ;;
        --check)    CHECK=true ;;
        --dry-run)  DRY_RUN=true ;;
        --pin)      PIN_FLOATING=true ;;
        --files)    IFS=',' read -r -a FILES <<< "$2"; shift ;;
        --help|-h)  usage; exit 0 ;;
        *)          echo "Unknown option: $1" >&2; exit 2 ;;
    esac
    shift
done

# -----------------------------------------------------------------------------
resolve_latest() {
    local url="https://api.github.com/repos/${THEME_REPO}/releases/latest"
    local body
    if [[ -n "${GH_TOKEN:-}${GITHUB_TOKEN:-}" ]]; then
        body=$(curl -sSf -H "Authorization: Bearer ${GH_TOKEN:-$GITHUB_TOKEN}" \
                    -H "Accept: application/vnd.github+json" "$url" 2>/dev/null) || return 1
    else
        body=$(curl -sSf -H "Accept: application/vnd.github+json" "$url" 2>/dev/null) || return 1
    fi
    printf '%s' "$body" | grep -m1 '"tag_name"' | sed -E 's/.*"tag_name":[[:space:]]*"v?([^"]+)".*/\1/'
}

if [[ "$USE_LATEST" == "true" ]]; then
    if ! VERSION=$(resolve_latest) || [[ -z "$VERSION" ]]; then
        echo "ERROR: could not resolve the latest ${THEME_REPO} release" >&2
        exit 1
    fi
fi

if [[ -z "$VERSION" ]]; then
    echo "ERROR: pass --version X.Y.Z or --latest" >&2
    exit 2
fi

# Default scan set: everywhere a pin is known to live. Gemfile.lock is excluded
# deliberately — it is regenerated by bundler, never hand-edited.
if [[ ${#FILES[@]} -eq 0 ]]; then
    while IFS= read -r f; do FILES+=("$f"); done < <(
        ls -1 _config*.yml _data/hub.yml Gemfile Gemfile.* 2>/dev/null | grep -v '\.lock$' || true
    )
fi

if [[ ${#FILES[@]} -eq 0 ]]; then
    echo "No candidate files found (looked for _config*.yml, _data/hub.yml, Gemfile*)" >&2
    exit 0
fi

# -----------------------------------------------------------------------------
# Does this file reference the theme at all (pinned, floating, or as a gem)?
# Distinct from current_pins: a floating `remote_theme: bamr87/zer0-mistakes`
# references the theme but pins no version, and --pin has to be able to find it.
has_theme_ref() {
    grep -qE "${THEME_REPO}|${THEME_GEM}" "$1" 2>/dev/null
}

# Report the versions currently pinned in a file, one per line.
current_pins() {
    local file="$1"
    grep -oE "(${THEME_REPO}@v?[0-9][^\"' ]*)|(${THEME_GEM}[\"'][[:space:]]*,[[:space:]]*[\"'][^\"']*)" "$file" 2>/dev/null |
        sed -E "s|.*${THEME_REPO}@v?||; s|.*[~><= ]||" | sort -u || true
}

rewrite() {
    local file="$1"
    NEW="$VERSION" perl -pi -e '
        next if /^\s*#/;                       # leave commented-out examples alone
        s{(remote_theme\s*:\s*["\x27]?bamr87/zer0-mistakes)\@v?[0-9][^"\x27\s]*}{$1\@v$ENV{NEW}}g;
        s{(theme_repo\s*:\s*["\x27]?bamr87/zer0-mistakes)\@v?[0-9][^"\x27\s]*}{$1\@v$ENV{NEW}}g;
        s{(gem\s+["\x27]jekyll-theme-zer0["\x27]\s*,\s*["\x27])([~><=]*\s*)[0-9][^"\x27]*}{$1$2$ENV{NEW}}g;
    ' "$file"

    if [[ "$PIN_FLOATING" == "true" ]]; then
        # Only after retagging, so an already-pinned ref is never double-tagged.
        NEW="$VERSION" perl -pi -e '
            next if /^\s*#/;
            s{(remote_theme\s*:\s*["\x27]?bamr87/zer0-mistakes)(?!\@)}{$1\@v$ENV{NEW}}g;
            s{(theme_repo\s*:\s*["\x27]?bamr87/zer0-mistakes)(?!\@)}{$1\@v$ENV{NEW}}g;
        ' "$file"
    fi
}

# -----------------------------------------------------------------------------
echo "Target zer0-mistakes version: ${VERSION}"
echo

changed=()
behind=()

for file in "${FILES[@]}"; do
    [[ -f "$file" ]] || continue

    has_theme_ref "$file" || continue

    before=$(cat "$file")
    pins_before=$(current_pins "$file")

    tmp=$(mktemp)
    cp "$file" "$tmp"
    rewrite "$file"
    after=$(cat "$file")

    if [[ "$before" == "$after" ]]; then
        if [[ -z "$pins_before" ]]; then
            echo "  ~ ${file} — floating on main (pass --pin to pin it at ${VERSION})"
        else
            echo "  ✓ ${file} — already at ${VERSION}"
        fi
        rm -f "$tmp"
        continue
    fi

    behind+=("$file")
    was=$(printf '%s' "$pins_before" | tr '\n' ' ' | sed 's/ *$//')
    echo "  ✗ ${file} — was ${was:-floating} → ${VERSION}"
    if [[ "$DRY_RUN" == "true" || "$CHECK" == "true" ]]; then
        diff -u "$tmp" "$file" | sed -n '4,$p' | sed 's/^/      /' || true
        cp "$tmp" "$file"          # restore: neither mode may write
    else
        changed+=("$file")
    fi
    rm -f "$tmp"
done

echo
if [[ ${#behind[@]} -eq 0 ]]; then
    echo "All pins already at ${VERSION}."
    exit 0
fi

if [[ "$CHECK" == "true" ]]; then
    echo "${#behind[@]} file(s) behind ${VERSION} — run without --check to update."
    exit 1
fi

if [[ "$DRY_RUN" == "true" ]]; then
    echo "[DRY RUN] would update ${#behind[@]} file(s)."
    exit 0
fi

echo "Updated ${#changed[@]} file(s) to ${VERSION}: ${changed[*]}"
echo
echo "Next: re-lock if a Gemfile changed (bundle lock --update=${THEME_GEM}),"
echo "      then run your site build before opening the PR."
